title: 1926 Digital Agency
email: info@1926agency.com
description: > # this means to ignore newlines until "baseurl:"
  A premier digital agency helping business' to increase efficiency and expand nationwide.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: http://www.twitter.com/1926marketing
facebook: https://www.facebook.com/1926digitalagency/
linkedin: https://www.linkedin.com/in/matthewmartin1926/
instagram: https://www.instagram.com/1926agency/

vlogs: false
blogs: false

assets:
  sources:
    - assets/javascripts
    - assets/stylesheets
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]

sass:
  sass_dir: assets/stylesheets
  style: compressed

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-assets

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
